<!-- List of content
  Pipe operator: %>%
  filter    -> selecting rows
  select    -> selecting cols
  mutate    -> add/change cols
  arrange   -> order rows
  summarize -> make summary
  group_by
  data pivoting: tydyr lib: pivot_longer (it is pivot in some languages) 
                            pivot_wider  (it is un-pivot sin some languages)
  string manipulation
  Web scraping
  Json parsing
-->

<!-- 1. Pipe operator -->
```{r}
library(magrittr)
```
```{r}
1:10 %>% mean()  # === mean(1:10)
```
```{r}
1:10 %>% mean() %>% floor() # === floor(mean(1:10))
```
```{r}
1:10 %>%                  # array
   mean(na.rm=FALSE) %>%  # mean
   floor()  %>%           # floor
   print()
```
```{r}
'Hello' %>%
   paste(" World")
```
<!-- 2. filter 
   
-->
```{r}
library(dplyr)
```
```{r}
starwars  # a dataframe
# Access cols. Eg. starwars['eye_color'] return single column dataframe
#                  starwars[['eye_color']] (or starwars$eye_color) return a vector 
```
```{r}
# starwars[['eye_color']] %>% class()
starwars[['eye_color']] %>% unique()
```
```{r}
# Select rows where eye_color = black
starwars  %>% 
   filter(eye_color == "black")  # NOTE: not use filter("eye_color" == "black") 
```
```{r}
# Select rows where ...
starwars  %>% 
   filter(eye_color == "black" & skin_color == "green") 

# Equivalent to
starwars  %>% 
   filter(eye_color == "black")  %>% 
   filter(skin_color == "green")
```
<!-- 3. select: selecting cols 
Helper functions: starts_with(), ends_with(), contains(), where()
-->
```{r}
colnames(starwars)
```
```{r}
starwars %>%
  select(2:7)

```

```{r}
starwars %>%
  select(c(1, 3, 5, 7))

starwars %>%
  select(c(7, 5, 3, 1))
```
```{r}
which(colnames(starwars) == 'hair_color')
```
```{r}
starwars %>%
  select(which(colnames(starwars) == 'height'): which(colnames(starwars) == 'birth_year'))

# Equivalent to
starwars %>%
  select(which(colnames(.) == 'height'): which(colnames(.) == 'birth_year'))

# Equivalent to
starwars %>%
  select(height: birth_year)

# Remove hair_color columns
starwars %>%
  select(height: birth_year, -hair_color)
```
```{r}
# everything() means all columns
df_tmp <- starwars %>%
  select(everything())

waldo::compare(df_tmp, starwars)
```
```{r}
# get cols from height: birth_year and everything else
starwars %>%
  select(height: birth_year, everything())  # 
```
```{r}
starwars %>%
  select(ends_with('_color')) 
```

```{r}
starwars %>%
  select(where(is.integer))  # choose only integer columns
                             # similarly: is.character
```
```{r}
starwars %>%
  select(!(c(height, birth_year)))  # choose all columns except height and birth_year
```
<!-- 4. Mutate: To add/change columns -->
```{r}
starwars %>%
  mutate(bmi = mass / ((height/100) ^2)) %>%  # Calculate column. BMI = mass/height [kg/m2]
  select(name, mass, height, bmi)  %>% 
  mutate(bmi = round(bmi, 2))                 # Change value of column

# Equivalent to
starwars %>%
  mutate(bmi = mass / ((height/100) ^2),
         bmi = round(bmi, 2)) %>% 
  select(name, mass, height, bmi) 
 
```
```{r}
starwars %>%
  select(name, homeworld, species)  %>%
  mutate(homeworld = as.factor(homeworld),
         species = as.factor(species))

# Equivalent to
starwars %>%
  select(name, homeworld, species)  %>%
  mutate(across(c(homeworld, species), as.factor))

# Equivalent to
starwars %>%
  select(name, homeworld, species)  %>%
  mutate(across(!name, as.factor))
```
<!-- 5. arrange -->

```{r}
starwars %>%
  arrange(height)  # sort asc dataframe by values of height column

starwars %>%
  arrange(desc(height))  # sort desc dataframe by values of height column

starwars %>%
  arrange(height, mass)  # sort asc dataframe by values of height column and then mass column
```  
<!-- 6. summarize -->
```{r}
starwars %>%  
  summarize(mean = mean(height, na.rm=TRUE), # make a col name "mean"
            num_rows = n() # count rows
            )
```
```{r}
starwars %>%  
  group_by(eye_color) %>%  
  summarize(mean = mean(height, na.rm=TRUE), # make a col name "mean"
            num_rows = n() # count rows
            )
```
```{r}
starwars %>%  
  group_by(eye_color) %>%  
  summarize(mean = mean(height, na.rm=TRUE), # make a col name "mean"
            num_rows = n() # count rows
            ) %>%  
  filter(num_rows > 1) %>%  # filter rows
  arrange(mean)   # asc sort mean column
```
<!-- 6. Pivot table: (change columns to rows) -->
```{r}
library(tidyr)

df <- tibble::tribble(
  ~Student, ~Test1, ~Test2,
 #--------/-------/-------
 'John',      'B',    NA,
 'Bob',        'A',   'C',
 'Adam',       'F', 'B'
)
df
```
```{r}
df_pivot <- pivot_longer(df, -Student, names_to = 'Assessment', values_to = 'Grade')
df_pivot
```
```{r}
df_unpivot <- pivot_wider(df_pivot, id_cols='Student', names_from = 'Assessment', values_from = 'Grade')
df_unpivot  #in fact, it is df
```
```{r}
waldo::compare(df, df_unpivot)
```
```{r}
relig_income
```
```{r}
relig_income_pivot <- pivot_longer(relig_income, -religion, names_to = 'income', values_to = 'count')
relig_income_pivot
```
```{r}
billboard
```
```{r}
billboard_pivot = billboard %>%
  pivot_longer(
    cols = starts_with('wk'),
    names_to = 'Week',
    values_to = 'rank'
  )
billboard_pivot
```
```{r}
billboard_pivot %>%
  group_by(track) %>%
  summarize(highest_rank = min(rank, na.rm = TRUE)) %>%
  arrange(highest_rank) # %>%
  # View()  # view as a seperate table in UI
```










