---
# install.packages("mongolite")
# https://jeroen.github.io/mongolite/query-data.html#query-syntax
# install.packages("DBI")
# install.packages("RPostgres")
---
```{r}
library(mongolite) 
# library(DBI)
```
```{r}
# Connect to the database and the desired collection as root:
db <- mongo(collection = "markers", 
            db = "facs",
            url = "mongodb://localhost:27017"
            )
db$count('{}')
```

```{r}
ind_code <- db$find('{"individualCode" : "APO180"}')
print(ind_code)
```
<!-- 2. Mongolite basics -->
```{r}
# library(tidyverse)
library(knitr)     # help run code
library(markdown)  # create markdown files i.e. pdf
library(mongolite) # Create connection/Interface R<-> Mongodb
```
```{r}
# Create Connection: 'localhost'
mng_conn<-mongo(collection = 'vidPrac',db='video_practice')
```
```{r}
# INSERT
fun_dta <- c('{"first_name":"Mr Bilbo","last_name": "Baggins","hobbies":["find rings",
"adventure","magic"]}','{"first_name":"Golumn","hobbies":["steal rings","bite people",
"talk to myself"]}')

mng_conn$insert(fun_dta)
```
```{r}
# FIND
mng_conn$find('{}')
```
```{r}
# UPDATE
mng_conn$update('{"first_name":"Golumn"}', 
                '{"$set":{"last_name": "The Lonely"}}',upsert=TRUE)
```
```{r}
# FIND
mng_conn$find('{}')
```
```{r}
# Add Element to specific document array
# Cut and paste your unique OID Number!
mng_conn$find('{}',fields='{"_id":1}')
```
```{r}
mng_conn$aggregate('[{"$match":{"_id":{"$oid":"60f96426ab5100001f0067d3"}}},
{"$addFields":{"hobbies":{"$concatArrays":["$hobbies",["Eat Fish"]]}}}]')

mng_conn$find('{}')
```
```{r}
# Add Element to List
mng_conn$update('{"_id":{"$oid":"60f96426ab5100001f0067d3"}}',
'{"$push":{"hobbies":"Eat Fish"}}',upsert=TRUE)
```
```{r}
mng_conn$find('{}')
```

```{r}
# Sorting
mng_conn$find(sort='{"first_name":1,"latst_name":1}')
```
```{r}
# Select by ID
mng_conn$find('{"_id":{"$oid":"60f96426ab5100001f0067d3"}}')
```
```{r}
# Download files
# create directory, within our CWD to store output file
dir.create('output_files_practice')

# send file to our directory:
mng_conn$export(file("output_files_practice/hobbits.json"))
```
```{r}
# Delete
mng_conn$remove('{"_id":{"$oid":"60f96426ab5100001f0067d3"}}')

# Find
mng_conn$find('{}')
```
```{r}
#Drop All Records But NOT collection
mng_conn$remove('{}')

# Find
mng_conn$find('{}')
```

```{r}
# Drop Collection:
mng_conn$drop()
```
```{r}
mng_conn$find('{}')
```
```{r}
# Shell Commands:
# ------------------------
# 
# Show Databases: show dbs
# 
# Check What Database You're Currently In: db
# 
# Enter/Use a Database: use dbnamehere
# 
# If this database is not currently used, it will be created otherwise it will just connect
# Show Collections: show collections
# 
# If your Collection Name has a Weird Name like spaces or hypens: db.getCollection(" your weird name").find()
# 
# Switch Database without Leaving Current Database: db.getSiblingDB('fromCurrentDB')
# 
# This is particularly useful when writing a script and you cannot access a database using the use db method.
# Exit MongoDB: quit()
# 
# Help: db.help
# 
# This will show all of the functions/methods available to you
```

<!-- 3. INSERT df to Mongodb -->
```{r}
library(knitr)     # help run code
library(markdown)  # create markdown files i.e. pdf
library(dplyr)
library(mongolite) # Create connection/Interface R<-> Mongodb
library(jsonlite)  # send files to Mongo
```
```{r}
db <- mongo(collection = "test",
                  db = "R_test",
                  url = "mongodb://localhost:27017")

```
```{r}
# Queries: From Mongo to R
# find all rows:
n<-db$find('{}')

# get a glimpse (idea)
dplyr::glimpse(n)
```
```{r}
head(n)
```
```{r}

#Count all rows
db$count()
```
```{r}
name = c("AA", "BB", "CC")
age = c(10, 20, 18)
df = data.frame(name, age)
df
```
```{r}
db$insert(df)
```
```{r}
# Get df from csv file
df1 = data.table::fread("restaurant.csv")
df1
```
```{r} 
# get column names
names(df1)   
```
```{r}
# remove space from column  names
names(df1) = gsub(" ", "", names(df1))
```


























