---
title: "Data Preprocessing"
output: html_notebook
---
```{r}
library(dplyr)
library(tidyr)
library(skimr)
library(rsample)  # install.packages("rsample")
``` 
```{r}
starwars
View(starwars)
```
```{r}
skim(starwars)
```
```{r}
data <- starwars %>%
   select(height, mass, gender)
data
```
```{r}
data_split <- initial_split(data)  # initial_split(), training(),  testing() from rsample lib
data_train <- training(data_split)
data_test <- testing(data_split)
```

```{r}
data_train <- data_train %>%  
   mutate(BMI = mass / (height/100) ^2)  # unit kg/m2
data_train
```
<!-- To know missing values -->
```{r}
skim(data_train)

# or using
print("--------------Any missing values in any cols------------------------")
any(is.na(data_train))
```
```{r}
colSums(is.na(data_train))
```
```{r}
data_train_imputed =  data_train %>%
  drop_na(height, gender)  %>%  # drop NA in some cols
  mutate(mass = ifelse(is.na(mass), mean(mass, na.rm = TRUE), mass),
         BMI = ifelse(is.na(BMI), mean(BMI, na.rm=TRUE), BMI))
skim(data_train_imputed)
```
# Encoding Categorical Data
```{r}
iris
```
```{r}
iris %>%
  mutate(Species = as.integer(Species))
```
<!-- One Hot Encoding -->
```{r}
iris %>%
  mutate(Species_versicolor = ifelse(Species == "versicolor", 1, 0),
         Species_virginica = ifelse(Species == "virginica", 1, 0),
         )
```
```{r}
data_train_imputed_encoded <- data_train_imputed %>%
  mutate(gender_numeric = ifelse(gender == 'masculine', 1, 0)) %>%
  select(-gender)
data_train_imputed_encoded
```
<!-- Feature Scaling -->
```{r}
normalize <- function(feature){
  (feature - mean(feature)) / sd(feature)
}
```
```{r}
data_train_imputed_encoded_norm <- data_train_imputed_encoded %>%
   mutate_all(normalize)
```
<!-- Complete Preprocessing Pipeline -->

```{r}
data_train_pipeline <- data_train %>%  
  
  # Feature Engineering
  mutate(BMI = mass / (height/100) ^2)  %>%   # unit kg/m2
  
  # Missing values
  drop_na(height, gender)  %>%  # drop NA in some cols
  mutate(mass = ifelse(is.na(mass), mean(mass, na.rm = TRUE), mass),
       BMI = ifelse(is.na(BMI), mean(BMI, na.rm=TRUE), BMI)) %>% 

  # Encoding Categorical Values
  mutate(gender_numeric = ifelse(gender == 'masculine', 1, 0)) %>% # masculine: 1, feminine: 0
  select(-gender) %>% 
  
  # Normalize data
  mutate_all(normalize)

data_train_pipeline
```
<!-- Testing  -->
```{r}
# library(waldo)
waldo::compare(data_train_pipeline, data_train_imputed_encoded_norm)
```
<!-- Do all the pipeline by recipes. install.packages("recipes") -->
```{r}
library(recipes)
```
```{r}
# Manual way to do pipeline
# data_train_pipeline <- data_train %>%  
#   # Feature Engineering
#   mutate(BMI = mass / (height/100) ^2)  %>%   # unit kg/m2
#   # Missing values
#   drop_na(height, gender)  %>%  # drop NA in some cols
#   mutate(mass = ifelse(is.na(mass), mean(mass, na.rm = TRUE), mass),
#          BMI = ifelse(is.na(BMI), mean(BMI, na.rm=TRUE), BMI)) %>% 
#   # Encoding Categorical Values
#   mutate(gender_numeric = ifelse(gender == 'masculine', 1, 0)) %>% # masculine: 1, feminine: 0
#   select(-gender) %>% 
#   # Normalize data
#   mutate_all(normalize)

data_recipe <- data_train %>%
  recipe() %>%   # Need to call recipe() function
    step_mutate(BMI = mass / (height/100) ^2)  %>%   # unit kg/m2
    step_naomit(height, gender) %>%
    step_impute_mean(mass, BMI) %>%
    step_dummy(gender) %>%
    step_normalize(everything()) %>%
  prep()  # Need to call prep() function

data_recipe  
```
```{r}
juice(data_recipe)  # juice() to get actual data
```
<!-- Data Analysis -->
```{r}
library(ggplot2)
library(tibble)
library(dplyr)
```
```{r}
# ?diamonds
diamonds
```
```{r}
glimpse(diamonds)  # glimpse() from tibble
```
```{r}
summary(diamonds)
```
```{r}
str(diamonds)  # str: structure function
```
```{r}
dim(diamonds)  # dimension (shape of dataframe)
```
```{r}
skimr::skim(diamonds)
```
```{r}
View(diamonds)
```
```{r}
head(diamonds)
```
```{r}
tail(diamonds)
```
<!-- Visualize distributions -->
```{r}
ggplot(data=diamonds) + geom_bar(mapping = aes(x=cut))
```
```{r}
diamonds %>%
  count(cut)
```
```{r}
table(diamonds$cut)
```
```{r}
unique(diamonds$cut)
```
```{r}
levels(diamonds$cut)
```
```{r}
levels(diamonds$clarity)
```
```{r}
table(diamonds$cut, diamonds$clarity)  # count occurences in 2D
```
```{r}
diamonds %>%
  count(cut, clarity) %>%  # haveing 3 cols: cut, clarity and n
  arrange(n)  # desc(n)
```

```{r}
# bar chart with vertical stack color by clarity
ggplot(diamonds, aes(x=cut, fill=clarity)) + geom_bar()  

```
```{r}
# bar chart with horizontal stack color by clarity
ggplot(diamonds, aes(x=cut, fill=clarity)) + 
  geom_bar(position = "dodge") + 
  theme(axis.text.x = element_text(angle = 90))
```
```{r}
# bar chart with horizontal stack color by clarity
ggplot(diamonds, aes(x=cut, fill=clarity)) + 
  geom_bar(position = "dodge") + 
  coord_flip()
```
```{r}
# bar chart with horizontal stack color by clarity
ggplot(diamonds, aes(x=cut, fill=clarity)) + 
  geom_bar(position = "fill") +   # fill mean all the bar is scaled to 1
  ylab("Proportion")
```
```{r}
# table(diamonds$cut, diamonds$clarity)  # count occurences in 2D
prop.table(table(diamonds$cut, diamonds$clarity))  # show the value/sum
```
```{r}
# table(diamonds$cut, diamonds$clarity)  # count occurences in 2D
# prop.table(table(diamonds$cut, diamonds$clarity))  # show the percentage 
round(prop.table(table(diamonds$cut, diamonds$clarity))*100, 2)  # show the percentage
```

```{r}
ggplot(diamonds, aes(x=cut)) +
  geom_bar() +
  facet_wrap(~clarity)
```

<!-- Continous varaibles -->
```{r}
ggplot(data=diamonds) +
  geom_histogram(mapping = aes(x = carat),
                 binwidth = 0.5)
```
```{r}
diamonds %>%
  count(cut_width(carat, 0.5))
```
```{r}
smaller <- diamonds %>%
  filter(carat < 3)

ggplot(data=smaller) +
  geom_histogram(mapping = aes(x = carat),
                 binwidth = 0.1)
```
```{r}
ggplot(data=smaller, mapping = aes(x=carat, color=cut)) + 
  geom_freqpoly(binwidth = 0.1)
```
```{r}
ggplot(data=smaller) +
  geom_histogram(mapping = aes(x = carat),
                 binwidth = 0.01)
```
```{r}
ggplot(diamonds) +
  geom_histogram(mapping = aes(x = y),
                 binwidth = 0.5)
```
```{r}
ggplot(diamonds) +
  geom_histogram(mapping = aes(x = y), binwidth = 0.5) + 
  coord_cartesian(ylim = c(0, 50))
```
<!-- Outlier -->
```{r}
# Unusual diamonds
diamonds %>%
  filter(y <3 | y > 20) %>%
  select(price, x ,y, z) %>%
  arrange(y)
```
<!-- Missing values -->

```{r}
diamonds2 <- diamonds %>%
  filter(between(y, 3, 20))

ggplot(diamonds2) +
  geom_histogram(mapping = aes(x = y), binwidth = 0.5) 
```
```{r}
diamonds %>%
  mutate(y = ifelse(y < 3 | y > 20, NA, y))  %>%
  ggplot(aes(x=x, y=y)) +
  geom_point()
```
```{r}
diamonds %>%
  # mutate(y = ifelse(y < 3 | y > 20, NA, y))  %>%
  ggplot(aes(x=x, y=y)) +
  geom_point()
```
<!-- Covariation: Categorical vs. Continous:
  (1) geom_freqpoly for each categorical
  (2) Density plot for each categorical
  (3) Box plot for for each categorical 
-->
```{r}
ggplot(diamonds, aes(x = price)) + 
  geom_freqpoly(aes(color = cut), binwidth = 500)
```
```{r}
ggplot(diamonds) + 
  geom_bar(aes(x = cut))
```
```{r}
# Density plot: Area under curve = 1
ggplot(diamonds, aes(x = price, y = ..density..)) + 
  geom_freqpoly(aes(color = cut), binwidth = 500)
```
```{r}
# BOXPLOT
ggplot(diamonds, aes(x = cut, y = price)) + 
  geom_boxplot() # + coord_flip()
```
<!-- Categorical vs. Categorical 
  count()
-->
```{r}
ggplot(diamonds) + 
  geom_count(aes(x = cut, y = color))
```
```{r}
diamonds %>%
  count(color, cut) 
```
```{r}
diamonds %>%
  count(color, cut) %>%
  ggplot(aes(x = color, y =cut)) + 
  geom_tile(aes(fill = n))
```
<!-- Continous vs. Continous
  scatter plot()
-->
```{r}
ggplot(diamonds) + 
  geom_point(aes(x = carat, y = price), alpha=1/10)
```
```{r}
ggplot(data = smaller) + 
  geom_bin2d(aes(x = carat, y = price))
```
