---
title: "R Notebook"
output: html_notebook
---
<!-- iris dataframe -->
```{r}
iris
```
```{r}
dt <- iris
```

```{r}
View(data)  # to view a dataframe
```

```{r}
data()  # list all of built-in datasets in R
```
<!-- CREATE A DATAFRAME -->
```{r}
df <- data.frame(Name=c('Ali', 'Bob'), # a column name and value
                 Age=c(20, 30),        # a column name and value
                 PassExam=c(TRUE, FALSE)
                 )
df
```
```{r}
df['Name']   # return a dataframe
```
```{r}
class(df['Name'])   # === type() in Python
```

```{r}
df$Name  # === df[['Name']]: return a vector. 
```

```{r}
class(df$Name) # === class(df[['Name']])
```
```{r}
df[1:2]   # access column 1 to 2
```
```{r}
df[c(1, 3)]   # access column 1 and 3 only
```
```{r}
df[2, ]  # access row 2 and all columns
```
<!-- Helper functions -->
```{r}
df <- data.frame(id = letters[1:4], x = 1:4, y = 5:8)
df
```
```{r}
length(df)
```
```{r}
head(df, n = 3)  # get first 3 rows
```
```{r}
tail(df, n = 3)
```
```{r}
dim(df)  # nrow(df), ncol(df)
```
```{r}
str(df)  # structure of df
```
```{r}
names(df)  # === list(df.columns) in pandas
```
```{r}
rownames(df)   # like df.index in pandas
```
```{r}
nameVetor = sapply(df, class)  # apply a function (here is class) for each columns
nameVetor  
```
```{r}
class(nameVetor)
```
```{r}
summary(df)
```
<!-- DATAFRAMES: TIBBLES: install.packages("tibble") -->
```{r}
library(tibble)   
```
```{r}
tb <- as_tibble(iris)
tb
```
```{r}
class(tb)
```

```{r}
df <- tibble(id = letters[1:4], 
             x = 1:4, 
             y = 9,  # tibble will make it a vector with the same length
             z = x ^ 2 + y,  # calculate "z" column,
             test = rep(5, 4)
             )
df
```
```{r}
df1 = tribble(
   ~x, ~y, ~z,   # make column name x, y, z
   'a', 1, TRUE,
   'b', 2, FALSE
)
df1
```
```{r}
# Lubridate:  install.packages("tidyverse") or install.packages("lubridate")
df2 <- tibble(
  a = lubridate:: now() + runif(1e3) * 86400,
  b = lubridate::today() + runif(1e3) * 30,
  c = 1: 1e3,
  d = runif(1e3),  # runif: random uniform [0, 1]
  e = sample(letters, 1e3, replace=TRUE)
)
df2
```
```{r}
print(df2, 
      n=2,   # number of rows - will take effect in console
      width=Inf  # width of table. Eg. width=100
      )   
```

