---
title: "R Notebook"
output: html_notebook
---
<!-- 1. Relational Operators -->
```{r}
a <- c (1, 2, 5.5, 9)
b <- c(10, 2, 0.5, 20)
a > b
```
```{r}
a == b
```
```{r}
sum (a==b) > 0
```
```{r}
a != b
```
<!-- 2. Logical operator: & (AND), | (OR), ! (NOT) -->
```{r}
a <- c (TRUE, TRUE, FALSE, 9)
b <- c(FALSE, TRUE, 0.5, 20)
a & b  # element-wise
```
```{r}
!a
```
<!-- if...else if...else -->
```{r}
x = 10
if (x  >= 10){
  message('x = ', x)
  paste('x = ', x)
}
```
<!-- Loops : repeat, while, for-->
```{r}
chars = LETTERS[1:3]
for (char in chars){
  print(char)
}

# Equivalent to function programing
results <- lapply(chars, print)  # results is a list
unlist(results)   # change list to vector

# Use sappl: string apply
results <- sapply(chars, print)  
results
```
<!-- Functions: 
  Built-in func: seq(from = 3, to = 9, by=2)
                 sum(), mean()
  Custom func
-->
```{r}
func_x = function(x){
  x ^2
}
func_x(x = 1:5)
func_x(x = 5)
```
<!-- Packages 
install.packages("ggplot2")
install.packages(c("ggplot2", "corrr"))  # install 2 packages

old.packages()  # packages need to update

browseVignettes(package = "ggplot2")  # open browser of this package
-->

<!-- Factors -->
```{r}
data <- c("A", "B", 'c', 'd', "B", "B", 'd')
print(c('data=',  data))

# factor is to transform categorical items to integer number
data_factor <- factor(data)
#print(data_factor)
#print(c('data_factor=', data_factor))
print(levels(data_factor))
print(as.integer(data_factor))
```
```{r}
sort(data_factor)
```
```{r}
as.integer(sort(data_factor))
```
```{r}
data_factor_set_level <- factor(data_factor, levels = c('B', 'c', 'd', 'A'))
data_factor_set_level
```
```{r}
as.integer(data_factor_set_level)
```
```{r}
sort(data_factor_set_level)
```
```{r}
table(data_factor_set_level)  # give the frequency of each value
```
```{r}
# install.packages("tidyverse")
library(forcats)

fct_infreq(data_factor_set_level)  # order by frequency
```
<!-- Date and times -->
```{r}
library(lubridate)
```
```{r}
today()
class(today())
now()
class(now())
ymd("2021-October-07")
ymd(20211007)
mdy("October 7th, 2021")
dmy("07-October, 2021")
ymd_hms("2021-October-07 12:10:09")  # mdy_hms(), mdy_hm(),...
```
<!-- Functional Programming: rep -->
```{r}
rep(6, 5)   # repeat 6 in 5 times
values = lapply(rep(6, 5), runif)  # running runif repeat 2 in 5 times
values
lapply(values, mean)
```
```{r}
mtcars
car_names <- rownames(mtcars)
car_names
unlist(lapply(car_names, nchar))  # nchar(): return number of characters

which(car_names == "Toyota Corolla")  # index where car name is "Toyota Corolla"
```


















