---
title: "Vector"
output: html_notebook
---
```{r}
(x <- 1:10)
```
<!-- Make a seq.  -->
```{r}
x <- seq(from=1, to=10, by=2)
print(x)
```
<!-- Assignment <-    Also can use =  -->
<!-- Note: = can mean assignment, function argument binding or case statement depending on context. -->
```{r}
y = seq(from=1, to=10, by=2)
print(y)
```
<!-- Broad casting -->
```{r}
x + 5 
```
<!-- Elementwise for 2 vectors with the same length -->
```{r}
z = x + y
z
```
<!-- Subset of a vector -->
```{r}
xx = x[1:3]
xx
```
<!-- Access one element -->
```{r}
x3 = x[3]
x3
```
<!-- Remove one element. Note: index in R comes from 1 (NOT 0) -->
```{r}
x_except_index_3 = x[-3]
x_except_index_3
```
<!--NA ‘Not Available’ / Missing Values  
 At console >?NA   can see the documentation of NA
-->
```{r}
x <- c(20.7, NA, 10)
x
```
<!-- Check NA:  is.na(a_value), anyNA(a_vector) -->
```{r}
value1 = 'test'
print(is.na(value1))

value2 = NA
print(is.na(value2))

print(anyNA(c(10, "test", 90.1)))
```
<!-- Coercion / casting -->
```{r}
xx <- c(10, 20.9, 'aa')  # coercion to character type (string)
xx
```
```{r}
xx <- c(TRUE, 9, FALSE)  # coercion to integer. TRUE: 1, FALSE: 0
xx
```
```{r}
xx <- c(TRUE, 'a', 9, FALSE)  # coercion to character type (string). 
                              #TRUE: "TRUE", FALSE: "FALSE"
xx
```
```{r}
xx <- c(as.character(10), as.character(as.numeric(TRUE)), 'aa') # explicit way 
xx
```
<!-- Vector naming -->
```{r}
x <- 1:3
print(x)
name = names(x)  # does x have a name?
print(name)      # NULL: meaning no name
```
```{r}
letters # R provides a list of lower-case letters from 'a' to 'z'
```
```{r}
LETTERS # R provides a list of upper-case letters from 'A' to 'Z'
```
```{r}
LETTERS[1:3]
```
```{r}
names(x) <- LETTERS[1:3]
x
# Output: Note A, B, C are names of x. Here x is still [1, 2 , 3]
# A B C 
# 1 2 3 
```
```{r}
x['A']
```
```{r}
xx <- c('A'=1, 'B'=2, 'C'=3)  # Assign names directly
xx
```
<!-- Append values to vector -->
```{r}
y <- c(1, 2, 3)     # y is vector 1, 2, 3
z <- c(y, 4, 5, 6)  # z is vector 1 2 3 4 5 6
zz <- c(y, z)       # zz is vector 1 2 3 1 2 3 4 5 6
zz
```
<!-- mean(), sum(), min(), max() of vector -->
```{r}
mean(y)
```
